name: oasis_paris
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.4
  firebase_app_check: ^0.3.2+5
  image_picker: ^1.0.7
  cached_network_image: ^3.2.0
  badges: ^3.1.2  # Ajout du package badges pour les notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profil.png
    - assets/map.png
    - assets/recherche.png
    - assets/reglages.png
    - assets/friends.png
