// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ2ZQq_wvt1rS0eevAUhAber3kWtYxUKQ',
    appId: '1:833089927966:web:14bfc44fca96db8585e70f',
    messagingSenderId: '833089927966',
    projectId: 'oasis-paris',
    authDomain: 'oasis-paris.firebaseapp.com',
    storageBucket: 'oasis-paris.firebasestorage.app',
    measurementId: 'G-4JN4GEKYDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCycmFPZ4ge_xc5zQmGWA-B0EiwJIXqB44',
    appId: '1:833089927966:android:87de1ee7abe4f09985e70f',
    messagingSenderId: '833089927966',
    projectId: 'oasis-paris',
    storageBucket: 'oasis-paris.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRiGBHULOVAcgZxABEvJ5aS2vaQ3cBPzI',
    appId: '1:833089927966:ios:d38d3ee27dd42eb585e70f',
    messagingSenderId: '833089927966',
    projectId: 'oasis-paris',
    storageBucket: 'oasis-paris.firebasestorage.app',
    iosBundleId: 'com.example.oasisParis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRiGBHULOVAcgZxABEvJ5aS2vaQ3cBPzI',
    appId: '1:833089927966:ios:d38d3ee27dd42eb585e70f',
    messagingSenderId: '833089927966',
    projectId: 'oasis-paris',
    storageBucket: 'oasis-paris.firebasestorage.app',
    iosBundleId: 'com.example.oasisParis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ2ZQq_wvt1rS0eevAUhAber3kWtYxUKQ',
    appId: '1:833089927966:web:945967197f2d0c5a85e70f',
    messagingSenderId: '833089927966',
    projectId: 'oasis-paris',
    authDomain: 'oasis-paris.firebaseapp.com',
    storageBucket: 'oasis-paris.firebasestorage.app',
    measurementId: 'G-NSSHBMMM2L',
  );
}
